openapi: "3.0.0"
info:
  version: 1.0.0
  title: Go Ride Share Account Logic API
  description: <h3> Internal Logic API for Account Operations

paths:                                         
  /api/VerifyLoginCredentials:
    post:
      summary: Get Login Tokens for App Access
      operationId: VerifyLoginCredentials
      tags:
        - Users
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyLoginCredentialsRequest'   
      responses:   
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyLoginCredentialsResponse"          

  /api/CreateUser:
    post:
      summary: Create a new Account
      operationId: CreateUser
      tags:
        - Users
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/CreatUserRequest'   
      responses:   
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyLoginCredentialsResponse"                         

components:
  schemas:
# VerifyLoginCredentialsRequest
    VerifyLoginCredentialsRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string      
          example: "test@email.com" 
        password:
          type: string      
          example: "testPassword"    
    VerifyLoginCredentialsResponse:
      type: object
      required:
        - email
        - password
      properties:
        logic_token:
          type: string      
          example: "oauth-token-generated-by-microsoft-for-logic-access"  
        db_token:
          type: string      
          example: "oauth-token-generated-by-microsoft-for-db-access"     
# CreateUser
    CreatUserRequest:
      type: object
      required:
        - email
        - password
        - name
        - bio
        - phone
        - photo
      properties:
        email:
          type: string      
          example: "test@email.com" 
        password:
          type: string      
          example: "testPassword"     
        name:
          type: string      
          example: "testName"     
        bio:
          type: string      
          example: "testBio"            
        phone:
          type: string      
          example: "4312245323"          
        photo:
          type: string      
          example: "testPhotoUrl"                  

