openapi: "3.0.0"
info:
  version: 1.0.0
  title: Go Ride Share Logic API
  description: <h3> Internal Logic API for Post Operations

paths:
  /api/savePost:
    post:
      summary: Save a completed post to the databse
      operationId: savePost
      tags:
        - Posts
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/SampleRequest'   
      responses:
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessfulResponse"       
        '400':
          description: Unsuccessful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnsuccessfulResponse"                
  /api/getPosts/{user_id}:
    get:
      summary: Save a completed post to the databse
      operationId: getPosts
      tags:
        - Posts
      parameters:
        - name: user_id
          in: path
          description: The ID of the user whos posts you want to query
          required: true
          schema:
            type: string
            format: string    
      responses:   
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostList"          
        '400':
          description: Unsuccessful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnsuccessfulResponse"                            

components:
  schemas:
    SampleRequest:
      type: object
      required:
        - name
        - originLng
        - originLat
        - destinationLng
        - destinationLat
        - departureDate
        - price 
        - seatsAvailable
      properties:
        name:
          type: string  
        originLng:
          type: number
          format: float  
        originLat:
          type: number
          format: float  
        destinationLng:
          type: number
          format: float  
        destinationLat:
          type: number
          format: float  
        departureDate:
          type: string  
        price:
          type: number
          format: float                 
        seatsAvailable:
          type: number
          format: float  
    SuccessfulResponse:
      type: object
      required:
        - post_id
      properties:
        post_id:
          type: string            
    UnsuccessfulResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string      
          default: "Incomplete post data" 












