openapi: "3.0.0"
info:
  version: 1.0.0
  title: Go Ride Share Logic API
  description: <h3> Internal Logic API for Logic Operations

paths:
  /api/savePost:
    post:
      summary: Save a completed post to the databse
      operationId: savePost
      tags:
        - Posts
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/Post'   
      parameters:
        - name: X-User-ID
          in: header
          required: true
          schema:
            type: string
        - name: X-Db-Token
          in: header
          required: true
          schema:
            type: string       
      responses:
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessfulSavePostResponse"       
        '400':
          description: Unsuccessful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnsuccessfulSavePostResponse"                
  /api/getPosts/{userId}:
    get:
      summary: Queries a users posts from the databse
      operationId: getPosts
      tags:
        - Posts
      parameters:
        - name: userId
          in: path
          description: The ID of the user whos posts you want to query
          required: true
          schema:
            type: string
            format: string    
        - name: X-User-ID
          in: header
          required: true
          schema:
            type: string
        - name: X-Db-Token
          in: header
          required: true
          schema:
            type: string                
      responses:   
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostList"          
        '400':
          description: Unsuccessful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnsuccessfulGetPostResponse"                            
  /api/getUser:
    get:
      summary: Queries a users Profile from the DB
      operationId: getUser
      parameters:
        - name: X-User-ID
          in: header
          required: true
          schema:
            type: string
        - name: X-Db-Token
          in: header
          required: true
          schema:
            type: string  
      tags:
        - Users
      responses:   
        '200':
          description:  Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"            

components:
  schemas:
    Post:
      type: object
      required:
        - name
        - originLng
        - originLat
        - destinationLng
        - destinationLat
        - departureDate
        - price 
        - seatsAvailable
      properties:
        name:
          type: string  
        originLng:
          type: number
          format: float  
        originLat:
          type: number
          format: float  
        destinationLng:
          type: number
          format: float  
        destinationLat:
          type: number
          format: float  
        departureDate:
          type: string  
        price:
          type: number
          format: float                 
        seatsAvailable:
          type: number
          format: float  
    SuccessfulSavePostResponse:
      type: object
      required:
        - post_id
      properties:
        post_id:
          type: string            
    UnsuccessfulSavePostResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string      
          default: "Incomplete post data" 
    PostList:
      type: object
      properties:
        post_id:
          type: array
          items:
            $ref: '#/components/schemas/Post'                     
    User:
      type: object
      required:
        - email
        - password
        - name
        - bio
        - phone
        - photo
      properties:
        email:
          type: string      
          example: "test@email.com" 
        password:
          type: string      
          example: "testPassword"     
        name:
          type: string      
          example: "testName"     
        bio:
          type: string      
          example: "testBio"            
        phone:
          type: string      
          example: "4312245323"          
        photo:
          type: string      
          example: "testPhotoUrl"   
    UnsuccessfulGetPostResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string      
          example: "Failed to get posts" 